### ISSUE TITLE
Can't install on company laptop due to Defender SmartScreen

### ISSUE THREAD

**Issue by mhoogenbosch** [jimmyeao/TEAMS2HA#3]
When trying to install on my laptop device, I'm presented the following error:

![image](https://github.com/jimmyeao/TEAMS2HA/assets/36899598/81bf1db3-f89b-4a75-b699-20c5e17986fe)

I think this has to do something with the signing of the exe file.

**Comment by jimmyeao** [comment]
Not much I can do about this, you will need to speak to your local IT team to get the app approved.
I used to sign apps, but code signing certificates have become so expensive I can no longer do this :(
You can try these steps:
Right-click the setup.exe
Select “Properties”
Check “Unblock”
Click “OK”.

**Comment by jimmyeao** [comment]
This should be validated by MS now :)
