### ISSUE TITLE
MQTT over websockets

### ISSUE THREAD

**Issue by mekaneck** [jimmyeao/TEAMS2HA#32]
**Is your feature request related to a problem? Please describe.**
I'd like to use this program on a computer that is often on VPN, and therefore I need to connect to my MQTT server which would be on an external network. In order to set up my MQTT server to handle requests from the outside world I need to configure my reverse proxy for that purpose. However setting up a reverse proxy is easy for HTTP(s) and not so easy for other protocols.

**Describe the solution you'd like**
I'd like MQTT over websockets to be an option that can be selected

**Describe alternatives you've considered**
I've tried configuring NGINX proxy manager to use a stream and just forward the TCP packets, but that doesn't allow using a subdomain and also requires handling the TLS via some other means and requires exposing another port to the internet.

**Comment by jimmyeao** [comment]
Thanks, I'll take a look at implimenting this!

**Comment by jimmyeao** [comment]
OK, progress i have this now:
![image](https://github.com/jimmyeao/TEAMS2HA/assets/5197831/a56f1655-3e38-4f16-95a6-efbd146c5ef9)
and NGINX Proxy Manager set to accept https and forward to 9001
Mosquitto is configured with letsencrypt:
```
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d


allow_anonymous false
password_file /etc/mosquitto/passwd

listener 1883

listener 8883
cafile /etc/mosquitto/certs/fullchain.pem
certfile /etc/mosquitto/certs/cert.pem
keyfile /etc/mosquitto/certs/privkey.pem


listener 9001
protocol websockets
cafile /etc/mosquitto/certs/fullchain.pem
```
and all appears to be working. I have some tests to walk through to make sure everything is good and nothing is broken, then I'll release it, or in the meantime, you can pull the dev branch and try it yourself if you have VIsual Studio 2022

**Comment by jimmyeao** [comment]
Update pushed, let me know how you get on

**Comment by mekaneck** [comment]
This works perfectly, this is fantastic! Thank you!!

**Comment by mekaneck** [comment]
One minor bug I noticed, and I can't tell if this is related to MQTT with Websockets or not (since I can only test with Websockets enabled), but the MQTT connection status shows correctly in the window when open, but shows incorrectly when viewing the right-click menu when minimized.

Both images below were taken when MQTT server was connected and communicating normally:

From open window:
- ![image](https://github.com/jimmyeao/TEAMS2HA/assets/48502913/f6c57906-767a-40bc-bafd-0e8cd96fc5ba)

From right-click menu from system tray while app is minimized. Note that MQTT says "disconnected" even though it is not.
- ![image](https://github.com/jimmyeao/TEAMS2HA/assets/48502913/c6fb0c11-ebb1-44bb-ba20-4fedc3a4f682)

**Comment by jimmyeao** [comment]
Thanks, ill look into this!

**Comment by jimmyeao** [comment]
Fix implemented, will be in the next release

**Comment by jimmyeao** [comment]
closed in new release
