### ISSUE TITLE
Change domains to binary_sensor and bring them into a single MQTT device

### ISSUE THREAD

**Issue by mekaneck** [jimmyeao/TEAMS2HA#39]
Couple suggestions which are somewhat related:

- Change domains of all 8 entities (currently `switch` and `sensor`) to `binary_sensor`. This is the correct domain type for something that can only be monitored and not controlled from HA, and can only have a state of `on` or `off` (or `true`/`false`). Unless I've missed something and your intention is to enable HA to control the mute, video, hand raise, and background blur?

- Create a common device for all entities so that they show up under the MQTT integration in HA.
  - I see that the `isinmeeting` entity has a device defined, but the identifiers need to be a list `"identifiers": [ "MyPrefix" ],` instead of a string `"identifiers": "MyPrefix",`. 
  - All 7 other entities should have the same device dictionary (or at a minimum a device dictionary with the same `identifiers` list) in order to be grouped into the same device in HA.
  - All keys should normally be all lowercase (e.g. `device` instead of `Device`) and make sure the underscores are correct (`sw_version` instead of `SwVersion`). See [example in HA docs](https://www.home-assistant.io/integrations/mqtt/#sensors). 

I've created auto-discovered MQTT entities in HA previously so if this is something you decide to implement let me know if I can answer any questions on it. I don't know C# but I am pretty familiar with HA.

**Comment by jimmyeao** [comment]
HA Can control the Mute, Video, Blur and hand raised (this is by design) but I'll look into your other suggestions. I'm OK with C# but mqtt/ha stuff is relativley new to me

**Comment by jimmyeao** [comment]
Almost there, but this will break current entity names:
![image](https://github.com/jimmyeao/TEAMS2HA/assets/5197831/c9d75293-0b39-4c21-9949-8c54ef06bfe5)

**Comment by jimmyeao** [comment]
as an update, the next version will move to binary sensors, and add a new sensor for whether or not teams is running

**Comment by mhoogenbosch** [comment]
I see this is now working, i just updated to 346, which isn't in the release section yet. ;-)

But it works. Unfortunately i now have multipe sensors. Have to get rit of a few to push the new ones to the correct names so my automation's will work.

**Comment by bluemryld** [comment]
Yeah, we are working on cleaning up the sensors.

**Comment by mhoogenbosch** [comment]
> Yeah, we are working on cleaning up the sensors.

I cleaned them myself with MQTT explorer, and all is fine now. Thanks !

**Comment by jimmyeao** [comment]
latest release has moved to binary sensors https://github.com/jimmyeao/TEAMS2HA/releases/tag/V1.1.0.501
