### ISSUE TITLE
Additional Windows features (standby / hibernate) 

### ISSUE THREAD

**Issue by mhoogenbosch** [jimmyeao/TEAMS2HA#45]
I don't know if this would be possible, but would it be possible to reboot or push the Windows client to standby or hibernate with your app. I know this isn't really related to TEAMS2HA, but this would mean I could ditch some other tool for putting the device into standby.

**Comment by bluemryld** [comment]
In theory it could, but its probably outside the scope of Teams2HA.
Whats the requirement? Hibernate/standby/reboot based on a MQTT message from HA?

**Comment by mhoogenbosch** [comment]
> In theory it could, but its probably outside the scope of Teams2HA. Whats the requirement? Hibernate/standby/reboot based on a MQTT message from HA?

I leave my laptop at my home office. I have an automation telling my device to go into standby mode when I leave the room (based on espresence). 

I'd imagine standby or hibernate wouldn't make a big difference in coding (and TBH I don't really know this) but I'd also imagine different people use different styles of controlling the device.

**Comment by jimmyeao** [comment]
Hi, after some consideration, we have decided we wont be putting this functionality into this app, however I am going to look at writing a simple app that will be independent and will achieve this :)

**Comment by markmghali** [comment]
> > In theory it could, but its probably outside the scope of Teams2HA. Whats the requirement? Hibernate/standby/reboot based on a MQTT message from HA?
> 
> I leave my laptop at my home office. I have an automation telling my device to go into standby mode when I leave the room (based on espresence).
> 
> I'd imagine standby or hibernate wouldn't make a big difference in coding (and TBH I don't really know this) but I'd also imagine different people use different styles of controlling the device.
> 
> And I realize this is stretching it. It's in the name; it resolves around teams which maybe doesn't make sense to control the power scheme either. But I figured ; never hurts to ask ;-)

you could look into hass agent https://github.com/LAB02-Research/HASS.Agent

**Comment by mhoogenbosch** [comment]
> > > In theory it could, but its probably outside the scope of Teams2HA. Whats the requirement? Hibernate/standby/reboot based on a MQTT message from HA?
> > 
> > 
> > I leave my laptop at my home office. I have an automation telling my device to go into standby mode when I leave the room (based on espresence).
> > I'd imagine standby or hibernate wouldn't make a big difference in coding (and TBH I don't really know this) but I'd also imagine different people use different styles of controlling the device.
> > And I realize this is stretching it. It's in the name; it resolves around teams which maybe doesn't make sense to control the power scheme either. But I figured ; never hurts to ask ;-)
> 
> you could look into hass agent https://github.com/LAB02-Research/HASS.Agent

Yes, that works but is a huge app for my sole purpose to put my system to sleep. Unfortunately, I'm not in control of my own firewall, if I was, I would have utilized the notification settings, but i'm not. 

Non the less, the statement is clear, i'll close the issue. 

thanks!

**Comment by jimmyeao** [comment]
take a look at https://github.com/jimmyeao/PC2MQTT
