### ISSUE TITLE
Include Area path default

### ISSUE THREAD

**Issue by mhoogenbosch** [jimmyeao/TEAMS2HA#52]
It would be nice if you already can add an Area and it get's auto added to HA.

For me for example; My device should be added to 'kantoor' (translated home office)

**Comment by jimmyeao** [comment]
It looks like MQTT doesnt support setting the area directly, but it can be done through the GUI:
![image](https://github.com/jimmyeao/TEAMS2HA/assets/5197831/e8f1beac-5aad-4c9b-9a80-7e0134925473)

**Comment by mhoogenbosch** [comment]
Yes I know. But when deleting the device (ive done that a couple of times now because of the issues we were facing) you have to edit it every time the device get's added to HA.

I was hoping it could be a static field in your app. But if this isn't possible, than that's it. Thanks.
