### ISSUE TITLE
Auto reconnect when launching teams.

### ISSUE THREAD

**Issue by paulka007** [jimmyeao/TEAMS2HA#55]
**Is your feature request related to a problem? Please describe.**
As a part-time remote worker, I quit the ms-teams application when not on work time. However if Teams2HA is already started (ie "Run at windows boot" is enabled), teams does not connect. If I sign out, leaving teams running, it does connect correctly.
![image](https://github.com/jimmyeao/TEAMS2HA/assets/16636353/0b582090-7f29-436c-a812-6d8a52cec3f6)

**Describe the solution you'd like**
Teams2HA can start with windows, and when I choose to open teams, it connects correctly.

**Describe alternatives you've considered**
If there was a way to auto start Teams2HA after I launch ms-teams this might work, but doing it manually is really annoying. Or a reconnect button

**Comment by jimmyeao** [comment]
It should already do this, are you using the "new" teams or classic teams?
