### ISSUE TITLE
Add option to "keep application running when closed"

### ISSUE THREAD

**Issue by loryanstrant** [jimmyeao/TEAMS2HA#59]
It would be great if there was an option to keep the application running when closed, because I keep pressing this to close the window - but it exits the application.
I know that technically that is the exact function of that, BUT commonly for apps that sit in the tray, pressing the X only closes the window as opposed to the application itself.

<img width="592" alt="image" src="https://github.com/jimmyeao/TEAMS2HA/assets/51473494/dc9bdc86-e7df-4fac-9568-34261d4aa954">

**Comment by jimmyeao** [comment]
Not a bad idea :) I'll try and look at it later today if I can

**Comment by jimmyeao** [comment]
If you restart the app it should update, feature now implemented :)

**Comment by loryanstrant** [comment]
Love the quick action and improved functionality, thank you!
