### ISSUE TITLE
Incomming Call

### ISSUE THREAD

**Issue by jonny190** [jimmyeao/TEAMS2HA#63]
**Describe the solution you'd like**
Can we have a sensor for an incoming call (Voice or video)? As i'd like to be able to preemptively change the volume of a media player with the aim to pause the media player and adjust lights if i answer the call

**Describe alternatives you've considered**
I tried using the "isinmeeting" but found this a bit slow for the reaction time to complete the above

**Comment by jimmyeao** [comment]
I'll take a look, but I don't think Teams exposes this through the API

**Comment by jimmyeao** [comment]
The teams api doesn't expose this, so until they do, I won't be able to implement it, sorry

**Comment by jonny190** [comment]
Thanks for looking 👍
