### ISSUE TITLE
Sometimes a second sensor get created. 

### ISSUE THREAD

**Issue by mhoogenbosch** [jimmyeao/TEAMS2HA#64]
**Describe the bug**
As title suggests, I experience second and third sensors get's created. I don't know exactly when this happens. I think it has something to do with switching between docking station and back, but although I have been trying to reproduce it don't compute.

This image is from switch.martijnlaptop_isbackgroundblurred
![image](https://github.com/jimmyeao/TEAMS2HA/assets/36899598/636b1e2c-a554-4f3e-a8c5-d0ac1fa3d6b7)

I see a new one has been created switch.martijnlaptop_isbackgroundblurred_2

Same goes for lot's of other sensors but a few don't seem to be impacted such as (luckely) binary_sensor.martijnlaptop_isinmeeting, which I have based my automations on.

**Expected behavior**
Keep only one sensor, so only the original. And don't automatically add new sensors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 (23H2)
 - Browser [e.g. chrome, safari] Edge 127.0.2651.8 
 - Version [e.g. 22] 1.1.0.751

** Logs - (please complete the following information) **
 - THFHA Logs
[Teams2ha_Log20240626.log](https://github.com/user-attachments/files/15987283/Teams2ha_Log20240626.log)

- Windows Application logs from event viewer

**Additional context**

**Comment by jimmyeao** [comment]
Hmm, when you say switching between docking station and back, Im guessing the network connection gets interrupted? I'll take a look tomorrow and try and add some logic to prevent duplicate sensors being created.

**Comment by jimmyeao** [comment]
Could you confirm this replicates the issue:
![image](https://github.com/jimmyeao/TEAMS2HA/assets/5197831/ef5ed3fb-a490-420c-ae92-40238079ae25)
Here the sensors appear under both "ryzen" and then again individually as ryzen_sensor_name?

**Comment by jimmyeao** [comment]
Ok, I have had a stab at replicating this with no look so far - I deleted the above from MQTT and HA, will see if they re-appear. I tried to simulate plugging in to a docking station by disabling and re-enabling my network card, but it has yet to make a difference :/

**Comment by mhoogenbosch** [comment]
I now have a new sensor for 'isbackgroundblurred', and I just don't know why. Doesn't seem to be anything wrong. I'll try and see if I can figure it out a bit more. I'll now remove it all and let it recreate.

`{"name":"isbackgroundblurred","unique_id":"martijnlaptop_IsBackgroundBlurred","device":{"ids":["teams2ha_martijnlaptop"],"mf":"Jimmy White","mdl":"Teams2HA Device","name":"martijnlaptop","sw":"v1.0"},"icon":"mdi:blur-off","command_topic":"homeassistant/switch/martijnlaptop/isbackgroundblurred/set","state_topic":"homeassistant/switch/martijnlaptop/isbackgroundblurred/state","payload_on":"ON","payload_off":"OFF"}`

**Comment by jimmyeao** [comment]
Is that new or a duplicate? MS haven't been great with the API, you can toggle blur lots of times, and it never updates until you do something else, like mute/unmute. I've been trying to find out who to speak to in the engineering team at MS about this, but drawn a blank so far.

**Comment by mhoogenbosch** [comment]
I think it is mainly because the app sometimes crashes. Or to be honest, I don't know what happens. It somstimes just doesn't run, while I'd like it to always be running. 

I just received a new laptop device yesterday. For sure I know it was running this morning and now I just noticed (because the attic light was still turned on) it wasn't running anymore. Attached is my log file, don't know if you can get anything out of it. I can't find anything wrong in it.

Maybe there is a way to turn on a debug log ?

[Teams2ha_Log20240709 - kopie.log](https://github.com/user-attachments/files/16142850/Teams2ha_Log20240709.-.kopie.log)

**Comment by jimmyeao** [comment]
Hmm, nothing in there is standing out :/ I'll try and add some extended logging and push a new version, may take me a couple of days as I'm travelling on business, hopefully I can get to the bottom of it!

**Comment by jimmyeao** [comment]
I've pushed a new version with some additional logging. Also worth looking in the application logs when it happens to see if that throws up anything useful?

**Comment by jimmyeao** [comment]
Which sensors are you missing? I'll spin up a VM this week and see if I can replicate it.
It should look like this in MQTT/HA:
![image](https://github.com/user-attachments/assets/48db91fd-ac66-41fc-bc39-eb916f2cce93)

**Comment by mhoogenbosch** [comment]
in the bottom you have a teams running with status on and a unavailable. The one with the on status, would that be a _2 sensor?

**Comment by jimmyeao** [comment]
Yes, not sure how it managed to do that :/ is is indeed named `binary_sensor.access_fc3t9y3_teamsrunning_2`

**Comment by jimmyeao** [comment]
I've notice this recently with a few mqtt devices in Home Assistant, where for some reason a second sensor is getting created, so now I am not sure if this is Mosquito, home assistant or my app :(

**Comment by mhoogenbosch** [comment]
On my new laptop it has been running fine so far. Haven't noticed the new entities anymore. I just recieved a new new laptop. So ill test it again
