### ISSUE TITLE
[improvement] It is possible to start the program multiple times

### ISSUE THREAD

**Issue by mhoogenbosch** [jimmyeao/TEAMS2HA#8]
Every time you click the link from the start menu it starts

![image](https://github.com/jimmyeao/TEAMS2HA/assets/36899598/9757978b-ee89-428c-93e4-f354d08863ec)

**Comment by jimmyeao** [comment]
Thanks, I'll see if I can put a fix in for this

**Comment by jimmyeao** [comment]
This will be fixed in the next version, to be released this weekend

**Comment by jimmyeao** [comment]
Fixed in new release 1.1.08
